### ISSUE TITLE
req/all/faa-users.php includes credentials

### ISSUE THREAD

**Issue by tylerthetiger** [airmencoders/hawgops#2]
The file req/all/faa-users.php includes username/password/private key.  This file shouldn't be included in the repo.  Additionally, I don't see where those variables are used anywhere in the project.

**Comment by chris-m92** [comment]
Thanks for the heads up! 
Yeah that was supposed to be moved to a different directory when I made this public with AirmenCoders. 
No worries though, with the FAA moving from NAIMES to SWIM for their Digital NOTAM service, I needed new credentials anyway.

The files were actually a holdover from a previous project that I was intending to integrate with Hawg Ops that I haven't yet had time to do so. I'm hoping that once I get some more stuff finished with the accounts / CAS Planner that I'll have the Weather Gonkulator up and running that will also pull the NOTAMs.
